### ISSUE TITLE
Discord Integration update moment

### ISSUE THREAD

**Issue by Oyplap** [Parkeymon/EXILED-SCP-SL-egg#10]
Joker updated Discord Integration with a reworked bot and updated plugin.

**Comment by Parkeymon** [comment]
yea ill check it out soon, Im assuming the install is broken now

**Comment by EsserGaming** [comment]
> yea ill check it out soon, Im assuming the install is broken now

Can confirm.. Since the bot is completely different with DI version 6.0.

**Comment by Parkeymon** [comment]
Fixed in v2.4.0
