### ISSUE TITLE
Time zone not setting properly.

### ISSUE THREAD

**Issue by ExPort-Gaming** [Parkeymon/EXILED-SCP-SL-egg#12]
Within the container, the timezone of the logs doesn't match the timezone of Pterodactyl. I have confirmed Pterodactyl's timezone is correct, as well as the servers and I have also rebuilt the server but it always shows UTC.

**Comment by ExPort-Gaming** [comment]
Just like to add, this also happens with other eggs/servers like Minecraft Vanilla.

**Comment by Parkeymon** [comment]
Yea you need to change the time zone in server configs if you want it to match as it is not set by the egg

**Comment by ExPort-Gaming** [comment]
Nevermind I didn't change the WINGS timezone, I am a certified smoothbrain.
