### ISSUE TITLE
Suggestion: Specific Exiled version option

### ISSUE THREAD

**Issue by Oyplap** [Parkeymon/EXILED-SCP-SL-egg#3]
Is it possible to have something like this in the egg:
![Schermafbeelding 2021-05-13 155513](https://user-images.githubusercontent.com/45702131/118135766-b042c700-b403-11eb-9aef-977302429e6a.png)

**Comment by EsserGaming** [comment]
Yes 😄

**Comment by EsserGaming** [comment]
I believe so, if not. Remove the -beta

**Comment by Oyplap** [comment]
I'll try today, thanks :)

**Comment by Parkeymon** [comment]
Beta tag is for SCPSL install not exiled. I can probably add beta tag for exiled

**Comment by Parkeymon** [comment]
added in pre-release

**Comment by Oyplap** [comment]
Thanks!
