### ISSUE TITLE
"Save Discord Bot Configs?" input is double

### ISSUE THREAD

**Issue by Oyplap** [Parkeymon/EXILED-SCP-SL-egg#9]
there are 2 "Save Discord Bot Configs?" inputs. Between "Install SCPStats?" and "Auto install custom plugins?".

I'm not sure if it was meant to be intentional.

**Comment by Parkeymon** [comment]
Probably a small oopsie, will be fixed with new discord integration update

**Comment by Parkeymon** [comment]
Fixed in v2.4.0
